import React, { Component } from "react";
import StripeCheckout from "react-stripe-checkout";
import { connect } from "react-redux";
import * as actions from "../actions";

class Payments extends Component {
	render() {
		// amount: US-dollar cents, token: expect a callback after auth payment, poorly called
		//debugger; // see the actual js code generated by this
		return (
			<StripeCheckout
				name="Emaily"
				description="$5 for 5 email credits"
				amount={500}
				token={(token) => this.props.handleToken(token)}
				stripeKey={process.env.REACT_APP_STRIPE_KEY}
			>
				<button className="btn">add credits</button>
			</StripeCheckout>
		);
	}
}

export default connect(null, actions)(Payments);
